version: 2.1
orbs:
  aws-cli: circleci/aws-cli@2.0.3

jobs:
  example-job:
    environment:
      AWS_REGION: us-west-2
      AWS_SECRET_ACCESS_KEY: nDDOhBWpxkNdZ+EMmAZGY0DjtFYxNb2PfSQziS2o 
      AWS_ACCESS_KEY_ID: AKIAUQOYV4M3JMIIQGNC
      AWS_ACCOUNT: 310228935478
    docker:
      # replace with your preferred image
      - image: cimg/base:stable
    steps:
      - aws-cli/install
      - run: aws --version
      - run: mkdir ~/aws && touch ~/aws/credentials
      - run: echo "[at-interviews] \n aws_access_key_id =  $AWS_ACCESS_KEY_ID \n aws_secret_access_key =  $AWS_SECRET_ACCESS_KEY" > ~/aws/credentials
      - run: cat ~/aws/credentials
      
workflows:
  example-workflow:
    jobs:
      - example-job