version: 2.1
orbs:
  aws-cli: circleci/aws-cli@2.0.3

jobs:
  example-job:
    docker:
      # replace with your preferred image
      - image: cimg/base:stable
    steps:
      - aws-cli/install
      - run: aws --version
      - run: aws eks update-kubeconfig --profile at-interviews --region us-west-2 --name at-interviews-cluster

        
workflows:
  example-workflow:
    jobs:
      - example-job