# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs


version: 2.1
jobs:
  build:
    docker:
      - image: ubuntu
    steps:
      - run:
          name: Installing Curl
          command: |
            apt update -y && apt upgrade -y
            apt install curl -y
            curl --version
            apt install python3-pip
            pip3 install awsebcli --upgrade
            aws --version

