jobs:
  example-job:
    docker:
      # replace with your preferred image
      - image: cimg/base:stable
    steps:
      - aws-cli/setup:
          aws-region: us-west-2 
          aws-secret-access-key: nDDOhBWpxkNdZ+EMmAZGY0DjtFYxNb2PfSQziS2o 
          aws-access-key-id: AKIAUQOYV4M3JMIIQGNC 
          profile-name: at-interviews 

workflows:
  example-workflow:
    jobs:
      - example-job
           
            

            
            
            

