# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs


version: 2.1
jobs:
  build:
    docker:
      - image: bearengineer/awscli-kubectl:latest
    steps:
      - run:
          name: Installing Curl
          command: |
            docker run -ti --rm bearengineer/awscli-kubectl

