# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs


version: 2.1
jobs:
  build:
    docker:
      - image: ubuntu
    steps:
      - run:
          name: Installing Curl
          command: |
            sudo apt update && sudo apt upgrade
            sudo apt install curl
            curl --version

