version: 2.1
orbs:
  aws-cli: circleci/aws-cli@2.0.3

jobs:
  example-job:
    environment:
      aws_region: us-west-2
      aws-secret-access-key: nDDOhBWpxkNdZ+EMmAZGY0DjtFYxNb2PfSQziS2o 
      aws-access-key-id: AKIAUQOYV4M3JMIIQGNC
    docker:
      # replace with your preferred image
      - image: cimg/base:stable
    steps:
      - aws-cli/install
      - run: aws --version
workflows:
  example-workflow:
    jobs:
      - example-job