# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs


version: 2.1
jobs:
  build:
    working_directory: ~/alltrails
    docker:
      - image: cimg/base:2021.04
    steps:
      - checkout
      # Whatever you want to do
      - run: git clone https://github.com/alltrails/at-interviews-helloworld.git
      - run: cd ~/alltrails && ls
      
    
           
            

            
            
            

