version: 2.1
orbs:
  aws-cli: circleci/aws-cli@2.0.3

jobs:
  example-job:
    environment:
      AWS_REGION: us-west-2
      AWS_SECRET_ACCESS_KEY: nDDOhBWpxkNdZ+EMmAZGY0DjtFYxNb2PfSQziS2o 
      AWS_ACCESS_KEY_ID: AKIAUQOYV4M3JMIIQGNC
      AWS_ACCOUNT: 310228935478
    docker:
      # replace with your preferred image
      - image: cimg/base:stable
    steps:
      - aws-cli/install
      - run: aws --version
      - run: mkdir ~/aws && touch ~/aws/credentials
      - run: echo "[at-interviews] \n aws_access_key_id =  $AWS_ACCESS_KEY_ID \n aws_secret_access_key =  $AWS_SECRET_ACCESS_KEY" | cat ~/aws/credentials
      - run: aws eks update-kubeconfig --profile at-interviews --region $AWS_REGION --name at-interviews-cluster
      - run: kubectl config use-context arn:aws:eks:$AWS_REGION:$AWS_ACCOUNT:cluster/at-interviews-cluster
      - run: aws ecr get-login-password --profile at-interviews --region $AWS_REGION docker login --username AWS --password-stdin \
             $AWS_ACCOUNT.dkr.ecr.us-west-2.amazonaws.com

workflows:
  example-workflow:
    jobs:
      - example-job